# Generated by Django 5.2.8 on 2025-11-28 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='título')),
                ('diretor', models.CharField(blank=True, max_length=255, verbose_name='diretor')),
                ('sinopse', models.TextField(blank=True, verbose_name='sinopse')),
                ('genero', models.CharField(blank=True, choices=[('acao', 'Ação'), ('aventura', 'Aventura'), ('comedia', 'Comédia'), ('drama', 'Drama'), ('ficcao', 'Ficção Científica'), ('terror', 'Terror'), ('suspense', 'Suspense'), ('animacao', 'Animação'), ('documentario', 'Documentário'), ('romance', 'Romance'), ('fantasia', 'Fantasia')], max_length=50, verbose_name='gênero')),
                ('temas', models.JSONField(blank=True, default=list, help_text="Lista de temas. Ex: ['ação', 'cyberpunk', 'ficção']", verbose_name='temas')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='nota do usuário')),
                ('data_assistida', models.DateField(verbose_name='data assistida')),
                ('duracao', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='duração (minutos)')),
                ('favorito', models.BooleanField(default=False, verbose_name='favorito')),
                ('foto', models.URLField(blank=True, max_length=500, null=True, verbose_name='foto (URL)')),
                ('poster', models.URLField(blank=True, max_length=500, null=True, verbose_name='poster (URL)')),
                ('ano', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1880), django.core.validators.MaxValueValidator(2100)], verbose_name='ano')),
                ('nacionalidade', models.CharField(blank=True, max_length=255, verbose_name='nacionalidade')),
                ('id_usuario', models.IntegerField(db_index=True, verbose_name='id do usuário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
