# Generated by Django 5.2.8 on 2025-11-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('nota', models.IntegerField()),
                ('dataAssistida', models.DateField()),
                ('favorito', models.BooleanField(default=False)),
                ('foto', models.URLField(blank=True, max_length=500, null=True)),
                ('temas', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('poster', models.URLField(blank=True, max_length=500, null=True)),
                ('nacionalidade', models.CharField(max_length=255)),
                ('id_usuario', models.IntegerField()),
            ],
        ),
    ]
