# Generated by Django 5.2.8 on 2025-11-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='sinopse',
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.TextField(blank=True, verbose_name='review'),
        ),
    ]
