# Generated by Django 5.2.8 on 2025-11-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_movie_sinopse_movie_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='temas',
        ),
    ]
