# Generated by Django 5.2.8 on 2025-11-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_movie_temas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(db_index=True, verbose_name='id do usuário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='backend.movie')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('id_usuario', 'filme')},
            },
        ),
    ]
